// data/db.ts

import type { Game, User, Tournament } from "@/types/types";

export const games: Game[] = [
    {
        id: "call-of-duty",
        title: "Call of Duty: Modern Warfare III",
        genre: "Shooter",
        rating: 4.7,
        image: "/games/COD mw3.jpeg",
        description:
            "A tactical first-person shooter delivering cinematic action and intense multiplayer gameplay.",
        releaseDate: "2023-11-10",
        developer: "Infinity Ward",
    },
    {
        id: "valorant",
        title: "Valorant",
        genre: "Tactical Shooter",
        rating: 4.8,
        image: "/games/valo.jpeg",
        description:
            "A 5v5 tactical shooter where precision and team coordination reign supreme.",
        releaseDate: "2020-06-02",
        developer: "Riot Games",
    },
    {
        id: "apex-legends",
        title: "Apex Legends",
        genre: "Battle Royale",
        rating: 4.6,
        image: "/games/apex.jpeg",
        description:
            "Fast-paced hero-based battle royale gameplay in a dynamic sci-fi world.",
        releaseDate: "2019-02-04",
        developer: "Respawn Entertainment",
    },
    {
        id: "fortnite",
        title: "Fortnite",
        genre: "Battle Royale",
        rating: 4.5,
        image: "/games/fortnite.jpeg",
        description:
            "The iconic battle royale blending shooting, building, and vibrant creativity.",
        releaseDate: "2017-07-21",
        developer: "Epic Games",
    },
    {
        id: "counter-strike-2",
        title: "Counter-Strike 2",
        genre: "Shooter",
        rating: 4.9,
        image: "/games/csgo2.jpeg",
        description:
            "A global phenomenon reimagined with Source 2, precision shooting, and competitive balance.",
        releaseDate: "2023-09-27",
        developer: "Valve",
    },
    {
        id: "dota-2",
        title: "Dota 2",
        genre: "MOBA",
        rating: 4.7,
        image: "/games/dota2.jpeg",
        description:
            "The legendary multiplayer online battle arena where strategy and skill collide.",
        releaseDate: "2013-07-09",
        developer: "Valve",
    },
    {
        id: "league-of-legends",
        title: "League of Legends",
        genre: "MOBA",
        rating: 4.6,
        image: "/games/lol.jpeg",
        description:
            "Five-on-five strategic battles that define competitive gaming worldwide.",
        releaseDate: "2009-10-27",
        developer: "Riot Games",
    },
    {
        id: "rocket-league",
        title: "Rocket League",
        genre: "Sports/Action",
        rating: 4.4,
        image: "/games/rocketleague.jpeg",
        description:
            "High-octane car soccer with crazy physics, skill shots, and spectacular goals.",
        releaseDate: "2015-07-07",
        developer: "Psyonix",
    },
    {
        id: "ea-sports-fc-26",
        title: "EA Sports FC 26",
        genre: "Sports",
        rating: 4.3,
        image: "/games/fifa26.jpeg",
        description:
            "The world's most popular football game with realistic gameplay and authentic leagues.",
        releaseDate: "2025-09-25",
        developer: "EA Sports",
    },
    {
        id: "minecraft",
        title: "Minecraft",
        genre: "Sandbox",
        rating: 4.8,
        image: "/games/minecraft.jpeg",
        description:
            "Endless creativity and adventure in a block-based sandbox world.",
        releaseDate: "2011-11-18",
        developer: "Mojang Studios",
    },
    {
        id: "skyrim",
        title: "The Elder Scrolls V: Skyrim",
        genre: "RPG",
        rating: 4.9,
        image: "/games/skyrim.jpeg",
        description:
            "Epic fantasy RPG set in a vast open world full of dragons, quests, and magic.",
        releaseDate: "2011-11-11",
        developer: "Bethesda Game Studios",
    },
    {
        id: "smite",
        title: "Smite",
        genre: "MOBA",
        rating: 4.1,
        image: "/games/smite.jpeg",
        description:
            "A third-person action MOBA where gods battle in mythical arenas.",
        releaseDate: "2014-03-25",
        developer: "Hi-Rez Studios",
    },
    {
        id: "starcraft-2",
        title: "StarCraft II",
        genre: "RTS",
        rating: 4.8,
        image: "/games/starcrafr2.jpeg",
        description:
            "A legendary real-time strategy experience with deep tactics and competitive play.",
        releaseDate: "2010-07-27",
        developer: "Blizzard Entertainment",
    },
    {
        id: "the-witcher-3",
        title: "The Witcher 3: Wild Hunt",
        genre: "RPG",
        rating: 4.9,
        image: "/games/thewitcher3.jpeg",
        description:
            "Embark on a vast open-world journey as Geralt in one of gaming’s finest RPGs.",
        releaseDate: "2015-05-19",
        developer: "CD Projekt Red",
    },
    {
        id: "elden-ring",
        title: "Elden Ring",
        genre: "Action RPG",
        rating: 4.9,
        image: "/games/eldenring.jpeg",
        description:
            "An open-world fantasy action RPG collaboration between FromSoftware and George R.R. Martin.",
        releaseDate: "2022-02-25",
        developer: "FromSoftware",
    },
    {
        id: "efootball-2026",
        title: "eFootball 2026",
        genre: "Sports",
        rating: 4.2,
        image: "/games/pes26.jpeg",
        description:
            "Konami’s free-to-play football sim featuring realistic physics and licensed teams.",
        releaseDate: "2025-09-10",
        developer: "Konami",
    },
    {
        id: "gran-turismo-7",
        title: "Gran Turismo 7",
        genre: "Racing",
        rating: 4.6,
        image: "/games/granturismo7.jpeg",
        description:
            "A love letter to car culture with incredible visuals and authentic driving realism.",
        releaseDate: "2022-03-04",
        developer: "Polyphony Digital",
    },
    {
        id: "forza-horizon-5",
        title: "Forza Horizon 5",
        genre: "Racing",
        rating: 4.8,
        image: "/games/forzahorizon5.jpg",
        description:
            "Explore Mexico in an expansive open-world racing adventure full of speed and freedom.",
        releaseDate: "2021-11-09",
        developer: "Playground Games",
    },
    {
        id: "clash-royale",
        title: "Clash Royale",
        genre: "Strategy",
        rating: 4.5,
        image: "/games/clashroyale.jpeg",
        description:
            "Build your deck and duel players in real-time battles blending tower defense and card strategy.",
        releaseDate: "2016-03-02",
        developer: "Supercell",
    },
];

export const users: User[] = [
    {
        id: "user1",
        username: "ShadowStrike",
        fullName: "Fady Shenoda",
        avatar: "/profiles/user1.jpg",
        level: 42,
        country: "Egypt",
        joinedAt: "2023-01-15",
        role: "player",
        bio: "Competitive gamer and tournament strategist. Loves shooters and team-based play.",
        favoriteGames: ["cod", "valorant", "apex", "cs2"],
        achievements: [
            { title: "Top 10 in COD World Series", year: 2024 },
            { title: "Valorant MVP - Riot Cup", year: 2023 },
        ],
        stats: {
            matchesPlayed: 258,
            tournamentsWon: 8,
            winRate: 0.67,
        },
    },
];

export const tournaments: Tournament[] = [
    {
        id: "cod-world-cup",
        title: "Call of Duty World Cup 2025",
        gameId: "cod",
        image: "/games/cod.jpg",
        prizePool: "$50,000",
        participants: 64,
        startDate: "2025-12-01",
        endDate: "2025-12-15",
        status: "upcoming",
    },
    {
        id: "valorant-champions",
        title: "Valorant Champions 2025",
        gameId: "valorant",
        image: "/games/valorant.jpg",
        prizePool: "$100,000",
        participants: 128,
        startDate: "2025-11-10",
        endDate: "2025-11-25",
        status: "ongoing",
    },
    {
        id: "apex-global-cup",
        title: "Apex Legends Global Cup",
        gameId: "apex",
        image: "/games/apex.jpg",
        prizePool: "$75,000",
        participants: 100,
        startDate: "2025-10-01",
        endDate: "2025-10-10",
        status: "finished",
    },
    {
        id: "dota2-international",
        title: "The International 2025",
        gameId: "dota2",
        image: "/games/dota2.jpg",
        prizePool: "$15,000,000",
        participants: 18,
        startDate: "2025-08-01",
        endDate: "2025-08-25",
        status: "finished",
    },
    {
        id: "cs2-major",
        title: "Counter-Strike 2 Major Championship",
        gameId: "cs2",
        image: "/games/cs2.jpg",
        prizePool: "$1,000,000",
        participants: 24,
        startDate: "2025-09-10",
        endDate: "2025-09-20",
        status: "finished",
    },
    {
        id: "rocket-league-worlds",
        title: "Rocket League World Championship",
        gameId: "rocket-league",
        image: "/games/rocket-league.jpg",
        prizePool: "$500,000",
        participants: 32,
        startDate: "2025-07-01",
        endDate: "2025-07-07",
        status: "finished",
    },
    {
        id: "fifa-world-championship",
        title: "FIFA eWorld Cup 2025",
        gameId: "fifa25",
        image: "/games/fifa25.jpg",
        prizePool: "$250,000",
        participants: 64,
        startDate: "2025-06-15",
        endDate: "2025-06-25",
        status: "finished",
    },
    {
        id: "tekken8-championship",
        title: "Tekken 8 World Championship",
        gameId: "tekken8",
        image: "/games/tekken8.jpg",
        prizePool: "$300,000",
        participants: 48,
        startDate: "2025-05-05",
        endDate: "2025-05-10",
        status: "finished",
    },
];