// data/db.ts

import type { Game, User, Tournament } from "@/types/types";

export const games: Game[] = [
    {
        id: "call-of-duty",
        title: "Call of Duty: Modern Warfare III",
        genre: "Shooter",
        rating: 4.7,
        image: "/games/COD mw3.jpeg",
        description:
            "A tactical first-person shooter delivering cinematic action and intense multiplayer gameplay.",
        releaseDate: "2023-11-10",
        developer: "Infinity Ward",
    },
    {
        id: "baldurs-gate-3",
        title: "Baldur’s Gate 3",
        genre: "RPG",
        rating: 4.9,
        image: "/games/baldursgate3.jpeg",
        description:
            "A rich D&D-based RPG offering deep storytelling, tactical combat, and freedom of choice.",
        releaseDate: "2023-08-03",
        developer: "Larian Studios",
    },
    {
        id: "ghost-of-tsushima",
        title: "Ghost of Tsushima",
        genre: "Action/Adventure",
        rating: 4.8,
        image: "/games/ghostoftsushima.jpeg",
        description:
            "A breathtaking open-world samurai epic set in feudal Japan.",
        releaseDate: "2020-07-17",
        developer: "Sucker Punch Productions",
    },
    {
        id: "god-of-war-ragnarok",
        title: "God of War Ragnarök",
        genre: "Action/Adventure",
        rating: 4.9,
        image: "/games/gowragnarok.jpeg",
        description:
            "Kratos and Atreus embark on a mythic father-son journey through Norse realms.",
        releaseDate: "2022-11-09",
        developer: "Santa Monica Studio",
    },
    {
        id: "hades",
        title: "Hades",
        genre: "Roguelike",
        rating: 4.8,
        image: "/games/hades.jpeg",
        description:
            "Battle your way out of the Underworld in this fast-paced rogue-like adventure.",
        releaseDate: "2020-09-17",
        developer: "Supergiant Games",
    },
    {
        id: "elden-scrolls-online",
        title: "The Elder Scrolls Online",
        genre: "MMORPG",
        rating: 4.3,
        image: "/games/tesonline.jpeg",
        description:
            "Massive online RPG set in the Elder Scrolls universe with co-op adventures.",
        releaseDate: "2014-04-04",
        developer: "ZeniMax Online Studios",
    },
    {
        id: "fall-guys",
        title: "Fall Guys",
        genre: "Party/Battle Royale",
        rating: 4.1,
        image: "/games/fallguys.jpeg",
        description:
            "Fun and chaotic obstacle course party game with up to 60 players.",
        releaseDate: "2020-08-04",
        developer: "Mediatonic",
    },
    {
        id: "among-us",
        title: "Among Us",
        genre: "Social Deduction",
        rating: 4.4,
        image: "/games/amongus.jpeg",
        description:
            "Work together—or betray your crew—in this wildly popular space-themed party game.",
        releaseDate: "2018-06-15",
        developer: "Innersloth",
    },
    {
        id: "doom-eternal",
        title: "DOOM Eternal",
        genre: "Shooter",
        rating: 4.7,
        image: "/games/doometernal.jpeg",
        description:
            "Rip and tear through demons in the ultimate fast-paced action FPS.",
        releaseDate: "2020-03-20",
        developer: "id Software",
    },
    {
        id: "the-last-of-us-2",
        title: "The Last of Us Part II",
        genre: "Action/Adventure",
        rating: 4.8,
        image: "/games/tlou2.jpeg",
        description:
            "A brutal, emotional narrative journey through a post-apocalyptic world.",
        releaseDate: "2020-06-19",
        developer: "Naughty Dog",
    },
    {
        id: "horizon-forbidden-west",
        title: "Horizon Forbidden West",
        genre: "Action RPG",
        rating: 4.7,
        image: "/games/horizonfw.jpeg",
        description:
            "Aloy explores a vast post-apocalyptic world filled with mechanical beasts.",
        releaseDate: "2022-02-18",
        developer: "Guerrilla Games",
    },
    {
        id: "metal-gear-solid-v",
        title: "Metal Gear Solid V: The Phantom Pain",
        genre: "Action/Stealth",
        rating: 4.8,
        image: "/games/mgsv.jpeg",
        description:
            "Open-world tactical espionage adventure from Hideo Kojima.",
        releaseDate: "2015-09-01",
        developer: "Kojima Productions",
    },
    {
        id: "bioshock-infinite",
        title: "BioShock Infinite",
        genre: "Shooter",
        rating: 4.6,
        image: "/games/bioshockinfinite.jpeg",
        description:
            "A visionary shooter set in the floating city of Columbia, mixing story and combat.",
        releaseDate: "2013-03-26",
        developer: "Irrational Games",
    },
    {
        id: "portal-2",
        title: "Portal 2",
        genre: "Puzzle",
        rating: 4.9,
        image: "/games/portal2.jpeg",
        description:
            "Ingenious physics-based puzzle game featuring dark humor and clever mechanics.",
        releaseDate: "2011-04-19",
        developer: "Valve",
    },
    {
        id: "subnautica",
        title: "Subnautica",
        genre: "Survival/Adventure",
        rating: 4.5,
        image: "/games/subnautica.jpeg",
        description:
            "Explore an alien ocean world filled with mystery and danger.",
        releaseDate: "2018-01-23",
        developer: "Unknown Worlds Entertainment",
    },
    {
        id: "no-mans-sky",
        title: "No Man’s Sky",
        genre: "Adventure/Exploration",
        rating: 4.2,
        image: "/games/nomanssky.jpeg",
        description:
            "An ever-expanding space exploration game across infinite procedurally generated worlds.",
        releaseDate: "2016-08-12",
        developer: "Hello Games",
    },
    {
        id: "terraria",
        title: "Terraria",
        genre: "Sandbox/Adventure",
        rating: 4.6,
        image: "/games/terraria.jpeg",
        description:
            "A pixel-art sandbox adventure of crafting, building, and exploration.",
        releaseDate: "2011-05-16",
        developer: "Re-Logic",
    },
    {
        id: "cuphead",
        title: "Cuphead",
        genre: "Platformer",
        rating: 4.5,
        image: "/games/cuphead.jpeg",
        description:
            "Beautifully hand-drawn run-and-gun platformer inspired by 1930s cartoons.",
        releaseDate: "2017-09-29",
        developer: "Studio MDHR",
    },
    {
        id: "nfs-payback",
        title: "Need for Speed: Payback",
        genre: "Racing",
        rating: 7.4,
        developer: "Ghost Games",
        releaseDate: "2017-11-10",
        description:
            "Set in the fictional Fortune Valley, Payback offers an action-packed story of revenge with three playable characters, high-speed chases, and cinematic car battles.",
        image: "/games/nfs-payback.jpeg"
    },
    {
        id: "nfs-heat",
        title: "Need for Speed: Heat",
        genre: "Racing",
        rating: 8.1,
        developer: "Ghost Games",
        releaseDate: "2019-11-08",
        description:
            "Race by day and risk it all by night in this adrenaline-fueled entry of the series, featuring Palm City’s open-world and a thrilling mix of legal and underground racing.",
        image: "/games/nfs-heat.jpeg"
    },
    {
        id: "the-crew-motorfest",
        title: "The Crew: Motorfest",
        genre: "Racing",
        rating: 8.3,
        developer: "Ubisoft Ivory Tower",
        releaseDate: "2023-09-14",
        description:
            "Jump into the Hawaiian island of O‘ahu and enjoy a car festival paradise full of high-speed challenges, open-world events, and community fun.",
        image: "/games/the-crew-motorfest.jpeg"
    },
    {
        id: "stardew-valley",
        title: "Stardew Valley",
        genre: "Simulation/RPG",
        rating: 4.9,
        image: "/games/stardewvalley.jpeg",
        description:
            "Relaxing farming and life simulation game loved by millions.",
        releaseDate: "2016-02-26",
        developer: "ConcernedApe",
    },
    {
        id: "civilization-6",
        title: "Civilization VI",
        genre: "Strategy",
        rating: 4.7,
        image: "/games/civ6.jpeg",
        description:
            "Build an empire to stand the test of time in this award-winning 4X strategy game.",
        releaseDate: "2016-10-21",
        developer: "Firaxis Games",
    },
    {
        id: "age-of-empires-4",
        title: "Age of Empires IV",
        genre: "RTS",
        rating: 4.4,
        image: "/games/aoe4.jpeg",
        description:
            "The return of the legendary real-time strategy series with historic battles and modern visuals.",
        releaseDate: "2021-10-28",
        developer: "Relic Entertainment",
    },
    {
        id: "valorant",
        title: "Valorant",
        genre: "Tactical Shooter",
        rating: 4.8,
        image: "/games/valo.jpeg",
        description:
            "A 5v5 tactical shooter where precision and team coordination reign supreme.",
        releaseDate: "2020-06-02",
        developer: "Riot Games",
    },
    {
        id: "apex-legends",
        title: "Apex Legends",
        genre: "Battle Royale",
        rating: 4.6,
        image: "/games/apex.jpeg",
        description:
            "Fast-paced hero-based battle royale gameplay in a dynamic sci-fi world.",
        releaseDate: "2019-02-04",
        developer: "Respawn Entertainment",
    },
    {
        id: "fortnite",
        title: "Fortnite",
        genre: "Battle Royale",
        rating: 4.5,
        image: "/games/fortnite.jpeg",
        description:
            "The iconic battle royale blending shooting, building, and vibrant creativity.",
        releaseDate: "2017-07-21",
        developer: "Epic Games",
    },
    {
        id: "counter-strike-2",
        title: "Counter-Strike 2",
        genre: "Shooter",
        rating: 4.9,
        image: "/games/csgo2.jpeg",
        description:
            "A global phenomenon reimagined with Source 2, precision shooting, and competitive balance.",
        releaseDate: "2023-09-27",
        developer: "Valve",
    },
    {
        id: "dota-2",
        title: "Dota 2",
        genre: "MOBA",
        rating: 4.7,
        image: "/games/dota2.jpeg",
        description:
            "The legendary multiplayer online battle arena where strategy and skill collide.",
        releaseDate: "2013-07-09",
        developer: "Valve",
    },
    {
        id: "league-of-legends",
        title: "League of Legends",
        genre: "MOBA",
        rating: 4.6,
        image: "/games/lol.jpeg",
        description:
            "Five-on-five strategic battles that define competitive gaming worldwide.",
        releaseDate: "2009-10-27",
        developer: "Riot Games",
    },
    {
        id: "rocket-league",
        title: "Rocket League",
        genre: "Sports/Action",
        rating: 4.4,
        image: "/games/rocketleague.jpeg",
        description:
            "High-octane car soccer with crazy physics, skill shots, and spectacular goals.",
        releaseDate: "2015-07-07",
        developer: "Psyonix",
    },
    {
        id: "ea-sports-fc-26",
        title: "EA Sports FC 26",
        genre: "Sports",
        rating: 4.3,
        image: "/games/fifa26.jpeg",
        description:
            "The world's most popular football game with realistic gameplay and authentic leagues.",
        releaseDate: "2025-09-25",
        developer: "EA Sports",
    },
    {
        id: "minecraft",
        title: "Minecraft",
        genre: "Sandbox",
        rating: 4.8,
        image: "/games/minecraft.jpeg",
        description:
            "Endless creativity and adventure in a block-based sandbox world.",
        releaseDate: "2011-11-18",
        developer: "Mojang Studios",
    },
    {
        id: "skyrim",
        title: "The Elder Scrolls V: Skyrim",
        genre: "RPG",
        rating: 4.9,
        image: "/games/skyrim.jpeg",
        description:
            "Epic fantasy RPG set in a vast open world full of dragons, quests, and magic.",
        releaseDate: "2011-11-11",
        developer: "Bethesda Game Studios",
    },
    {
        id: "smite",
        title: "Smite",
        genre: "MOBA",
        rating: 4.1,
        image: "/games/smite.jpeg",
        description:
            "A third-person action MOBA where gods battle in mythical arenas.",
        releaseDate: "2014-03-25",
        developer: "Hi-Rez Studios",
    },
    {
        id: "starcraft-2",
        title: "StarCraft II",
        genre: "RTS",
        rating: 4.8,
        image: "/games/starcrafr2.jpeg",
        description:
            "A legendary real-time strategy experience with deep tactics and competitive play.",
        releaseDate: "2010-07-27",
        developer: "Blizzard Entertainment",
    },
    {
        id: "the-witcher-3",
        title: "The Witcher 3: Wild Hunt",
        genre: "RPG",
        rating: 4.9,
        image: "/games/thewitcher3.jpeg",
        description:
            "Embark on a vast open-world journey as Geralt in one of gaming’s finest RPGs.",
        releaseDate: "2015-05-19",
        developer: "CD Projekt Red",
    },
    {
        id: "elden-ring",
        title: "Elden Ring",
        genre: "Action RPG",
        rating: 4.9,
        image: "/games/eldenring.jpeg",
        description:
            "An open-world fantasy action RPG collaboration between FromSoftware and George R.R. Martin.",
        releaseDate: "2022-02-25",
        developer: "FromSoftware",
    },
    {
        id: "efootball-2026",
        title: "eFootball 2026",
        genre: "Sports",
        rating: 4.2,
        image: "/games/pes26.jpeg",
        description:
            "Konami’s free-to-play football sim featuring realistic physics and licensed teams.",
        releaseDate: "2025-09-10",
        developer: "Konami",
    },
    {
        id: "gran-turismo-7",
        title: "Gran Turismo 7",
        genre: "Racing",
        rating: 4.6,
        image: "/games/granturismo7.jpeg",
        description:
            "A love letter to car culture with incredible visuals and authentic driving realism.",
        releaseDate: "2022-03-04",
        developer: "Polyphony Digital",
    },
    {
        id: "forza-horizon-5",
        title: "Forza Horizon 5",
        genre: "Racing",
        rating: 4.8,
        image: "/games/forzahorizon5.jpg",
        description:
            "Explore Mexico in an expansive open-world racing adventure full of speed and freedom.",
        releaseDate: "2021-11-09",
        developer: "Playground Games",
    },
    {
        id: "clash-royale",
        title: "Clash Royale",
        genre: "Strategy",
        rating: 4.5,
        image: "/games/clashroyale.jpeg",
        description:
            "Build your deck and duel players in real-time battles blending tower defense and card strategy.",
        releaseDate: "2016-03-02",
        developer: "Supercell",
    },
];

export const users: User[] = [
    {
        id: "user1",
        username: "ShadowStrike",
        fullName: "Fady Shenoda",
        avatar: "/profiles/user1.jpg",
        level: 42,
        country: "Egypt",
        joinedAt: "2023-01-15",
        role: "player",
        bio: "Competitive gamer and tournament strategist. Loves shooters and team-based play.",
        favoriteGames: ["cod", "valorant", "apex", "cs2"],
        achievements: [
            { title: "Top 10 in COD World Series", year: 2024 },
            { title: "Valorant MVP - Riot Cup", year: 2023 },
        ],
        stats: {
            matchesPlayed: 258,
            tournamentsWon: 8,
            winRate: 0.67,
        },
    },
];

export const tournaments: Tournament[] = [
    {
        id: "cod-world-cup",
        title: "Call of Duty World Cup 2025",
        gameId: "call-of-duty",
        game: "Call of Duty: Modern Warfare III",
        image: "/games/COD mw3.jpeg",
        prizePool: "$50,000",
        participants: 64,
        startDate: "2025-12-01",
        endDate: "2025-12-15",
        status: "upcoming",
        genre: "Shooter",
    },
    {
        id: "valorant-champions",
        title: "Valorant Champions 2025",
        gameId: "valorant",
        game: "Valorant",
        image: "/games/valo.jpeg",
        prizePool: "$100,000",
        participants: 128,
        startDate: "2025-11-10",
        endDate: "2025-11-25",
        status: "ongoing",
        genre: "Tactical Shooter",
    },
    {
        id: "apex-global-cup",
        title: "Apex Legends Global Cup",
        gameId: "apex-legends",
        game: "Apex Legends",
        image: "/games/apex.jpeg",
        prizePool: "$75,000",
        participants: 100,
        startDate: "2025-10-01",
        endDate: "2025-10-10",
        status: "finished",
        genre: "Battle Royale",
    },
    {
        id: "dota2-international",
        title: "The International 2025",
        gameId: "dota-2",
        game: "Dota 2",
        image: "/games/dota2.jpeg",
        prizePool: "$15,000,000",
        participants: 18,
        startDate: "2025-08-01",
        endDate: "2025-08-25",
        status: "finished",
        genre: "MOBA",
    },
    {
        id: "cs2-major",
        title: "Counter-Strike 2 Major Championship",
        gameId: "counter-strike-2",
        game: "Counter-Strike 2",
        image: "/games/csgo2.jpeg",
        prizePool: "$1,000,000",
        participants: 24,
        startDate: "2025-09-10",
        endDate: "2025-09-20",
        status: "finished",
        genre: "Shooter",
    },
    {
        id: "rocket-league-worlds",
        title: "Rocket League World Championship",
        gameId: "rocket-league",
        game: "Rocket League",
        image: "/games/rocketleague.jpeg",
        prizePool: "$500,000",
        participants: 32,
        startDate: "2025-07-01",
        endDate: "2025-07-07",
        status: "finished",
        genre: "Sports/Action",
    },
    {
        id: "ea-fc-world-cup",
        title: "EA Sports FC World Cup 2025",
        gameId: "ea-sports-fc-26",
        game: "EA Sports FC 26",
        image: "/games/fifa26.jpeg",
        prizePool: "$250,000",
        participants: 64,
        startDate: "2025-06-15",
        endDate: "2025-06-25",
        status: "finished",
        genre: "Sports",
    },
    {
        id: "tekken8-championship",
        title: "Tekken 8 World Championship",
        gameId: "tekken-8",
        game: "Tekken 8",
        image: "/games/tekken8.jpeg",
        prizePool: "$300,000",
        participants: 48,
        startDate: "2025-05-05",
        endDate: "2025-05-10",
        status: "finished",
        genre: "Fighting",
    },
    {
        id: "valorant-regional-cup",
        title: "Valorant Regional Cup – Europe",
        gameId: "valorant",
        game: "Valorant",
        image: "/games/valo.jpeg",
        prizePool: "$30,000",
        participants: 64,
        startDate: "2025-04-01",
        endDate: "2025-04-10",
        status: "finished",
        genre: "Tactical Shooter",
    },
    {
        id: "cod-pro-league",
        title: "Call of Duty Pro League 2025",
        gameId: "call-of-duty",
        game: "Call of Duty: Modern Warfare III",
        image: "/games/COD mw3.jpeg",
        prizePool: "$80,000",
        participants: 48,
        startDate: "2025-03-10",
        endDate: "2025-03-25",
        status: "finished",
        genre: "Shooter",
    },
    {
        id: "apex-legends-showdown",
        title: "Apex Legends Showdown",
        gameId: "apex-legends",
        game: "Apex Legends",
        image: "/games/apex.jpeg",
        prizePool: "$60,000",
        participants: 80,
        startDate: "2025-02-05",
        endDate: "2025-02-15",
        status: "finished",
        genre: "Battle Royale",
    },
    {
        id: "rocket-league-cup",
        title: "Rocket League Continental Cup",
        gameId: "rocket-league",
        game: "Rocket League",
        image: "/games/rocketleague.jpeg",
        prizePool: "$120,000",
        participants: 40,
        startDate: "2025-03-01",
        endDate: "2025-03-07",
        status: "finished",
        genre: "Sports/Action",
    },
    {
        id: "ea-fc-champions-league",
        title: "EA Sports FC Champions League 2025",
        gameId: "ea-sports-fc-26",
        game: "EA Sports FC 26",
        image: "/games/fifa26.jpeg",
        prizePool: "$400,000",
        participants: 64,
        startDate: "2025-04-15",
        endDate: "2025-04-30",
        status: "ongoing",
        genre: "Sports",
    },
    {
        id: "cs2-global-open",
        title: "CS2 Global Open 2025",
        gameId: "counter-strike-2",
        game: "Counter-Strike 2",
        image: "/games/csgo2.jpeg",
        prizePool: "$500,000",
        participants: 32,
        startDate: "2025-05-01",
        endDate: "2025-05-10",
        status: "ongoing",
        genre: "Shooter",
    },
    {
        id: "dota2-summer-cup",
        title: "Dota 2 Summer Cup 2025",
        gameId: "dota-2",
        game: "Dota 2",
        image: "/games/dota2.jpeg",
        prizePool: "$2,000,000",
        participants: 16,
        startDate: "2025-06-01",
        endDate: "2025-06-12",
        status: "upcoming",
        genre: "MOBA",
    },
    {
        id: "tekken8-asia-open",
        title: "Tekken 8 Asia Open 2025",
        gameId: "tekken-8",
        game: "Tekken 8",
        image: "/games/tekken8.jpeg",
        prizePool: "$100,000",
        participants: 40,
        startDate: "2025-02-01",
        endDate: "2025-02-05",
        status: "upcoming",
        genre: "Fighting",
    },
];
